### PR TITLE
Build v8 for linux_arm64

### PR DESCRIPTION
**Pull request by epk**
Follow up to https://github.com/rogchap/v8go/pull/202

Adds `linux/arm64` support

### CODE REVIEW

**Review by rogchap — APPROVED** [review]
Looks straight forward to me.

**Comment by colinking** [comment]
Thanks for opening this PR @epk! We tried this in [our downstream fork](https://github.com/airplanedev/v8go/pull/26/files) using the latest `master` and it is working great from our testing on a Linux VM on our M1 macs.

Would love to see this merge. Anything I help with here?

**Comment by genevieve** [comment]
The conflicts need to be resolved on this branch then it can be merged.

**Comment by epk** [comment]
Rebased on the latest master.

**Pull request merged**
