### PR TITLE
Fix value free panic on disposed isolate

### PR DESCRIPTION
**Pull request by inn0kenty**
See #81.

Possible solution with atomic "isolate disposed" flag.

### CODE REVIEW

**Comment by rogchap** [comment]
I don't think the issue is with the Isolate being disposed as this still panics without disposing the Isolate before the GC.
I've tracked it down to the way the value is created against the Isolate, but most values are created on the context.
We use an internal Context for BigInt values, so I will see if tracking new values against this internal context is better.

This is my current test cases that panics:

```go
func TestIsolateGarbageCollection(t *testing.T) {
	t.Parallel()

	iso, _ := v8go.NewIsolate()
	val, _ := v8go.NewValue(iso, "some string")
	fmt.Println(val.String())

	// iso.Dispose()

	runtime.GC() // force garbage collection

	time.Sleep(time.Second)
}
```

Thanks for taking a look into this.

**Comment by rogchap** [comment]
I need to fix up the CI for FOSSA too 😱

**Comment by inn0kenty** [comment]
Thank you for your work!

I suppose your test case also panics because GC execute isolate finalizer before value finalizer.

Try comment line https://github.com/rogchap/v8go/blob/9848a00f5cb55a1da3ec045dec61d353c4f98620/isolate.go#L103

**Comment by rogchap** [comment]
> I suppose your test case also panics because GC execute isolate finalizer before value finalizer.

Good point. 👍 

I'm thinking that using finalizes are just a bad idea, and too hard to coordinate between the C and Go worlds. 

When we create a new value, it's not attached to a context, but in order to return the contents of the value we need a context; so currently we use a single "internal" context for this.

With a regular user created Context, all values that are created on this context are attached to said context, so when we do `ctx.Close()` we release all the values that are tracked with that context.

I think for the new values that are created against just the Isolate, we should attach these values to the internal context vector. This way when we call `iso.Dispose()` we will free all the values created with this Isolate and then close the internal context, all be before disposing of the isolate.

This would eliminate the need for any finalizers on values, or contexts (you would HAVE To use `ctx.Close()` to avoid leaks), simplifying the Go code.

**Comment by inn0kenty** [comment]
I think removing finalizers is a good point.

Also as I see Value already have Context pointer. So, why NewValue can't take context instead of isolate as a first argument? In that case will be possible track values through provided context instead of internal.

https://github.com/rogchap/v8go/blob/794781e582f89ec88eed4f089cdc32c531e2940f/value.go#L22
https://github.com/rogchap/v8go/blob/794781e582f89ec88eed4f089cdc32c531e2940f/value.go#L44

**Comment by rogchap** [comment]
> Also as I see Value already have Context pointer. So, why NewValue can't take context instead of isolate as a first argument? In that case will be possible track values through provided context instead of internal.

Yea, it's slightly complicated with the V8 API: to "resolve" any Value (ie get the string or integer value) you require a Context, but to just create a Value you only need the Isolate. The reason for this is that you need to be able to set properties of the Object/Function Templates that can be use to create a context.
It would be counter intuitive to require a Context to create a Context.

FYI: I've created #86 which should fix your issue described here. I tested the finalizer for Templates and it seems fine/not effected, by disposing the Isolate.

Are you able to test your code against this fix?

**Comment by inn0kenty** [comment]
Thank you!

This fix works fine with my code.

**Comment by rogchap** [comment]
Closing as this was fixed in #86

**Pull request closed without merging**
