### PR TITLE
Build for linux/arm64 architecture

### PR DESCRIPTION
**Pull request by abeMedia**
This PR adds arm64 architecture (https://github.com/rogchap/v8go/issues/97).
I was trying to also get armv7 to work but struggling so doing that as a separate PR (https://github.com/abeMedia/v8go/pull/1).

Edit: just realised my IDE reformatted your YAML. 
Do you want me to revert old old formatting (i.e. 4 spaces indentation, not 2)?

### CODE REVIEW

**Comment by rogchap** [comment]
Thanks for the PR @abeMedia 
Will look in more details soon (looks fine from first glance)
Note to self: I really need to fix the build to handle FOSSA so that PRs from forks work better.

**Comment by abeMedia** [comment]
> Thanks for the PR @abeMedia
> Will look in more details soon (looks fine from first glance)
> Note to self: I really need to fix the build to handle FOSSA so that PRs from forks work better.

Nice one @rogchap! Would you like me to add tests for `arm64` by the way? Could be implemented using [uraimo/run-on-arch-action](https://github.com/uraimo/run-on-arch-action).

Also, do you have any idea why [this build for `armhf`](https://github.com/abeMedia/v8go/runs/2214996042?check_suite_focus=true) is failing? Would love to also get `armhf` working as that's what my infrastructure is mainly made up of.

**Comment by rogchap** [comment]
Hey @abeMedia 

Code looks good. I've updated to fix the FOSSA issue.
Would be good to add test for linux arm64, just so that we have a full test suite.

Looking at the build error for `armhf`... it's using the `-m32` flag which means it's trying to build for 32bit, so maybe getting getting messed up with 32 vs 64 bit libraries (don't know if this helps?)

**Comment by rogchap** [comment]
Hey @abeMedia, Apologies, there has been a lot of work done for Windows static binary and upgrades to V8 that has added quite a few conflicts.

**Comment by genevieve** [comment]
Closing since #223 was merged

**Pull request closed without merging**
